#ifndef RIVETKIT_GO_FFI_H
#define RIVETKIT_GO_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The single source of truth for the native ABI version.
 */
#define RK_ABI_VERSION 2

/**
 * Opaque structured error handle. Its contents are accessed as JSON.
 */
typedef struct RkError RkError;

/**
 * Opaque runner handle.
 */
typedef struct RkRunner RkRunner;

/**
 * An owned byte buffer allocated by Rust.
 */
typedef struct RkBytes {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} RkBytes;

typedef struct RkRunnerResult {
  struct RkRunner *runner;
  struct RkError *err;
} RkRunnerResult;

typedef struct RkPollResult {
  struct RkBytes payload;
  struct RkError *err;
} RkPollResult;

typedef struct RkSubmitResult {
  struct RkError *err;
} RkSubmitResult;

/**
 * Returns the native ABI version expected by the generated Go binding.
 */
uint32_t rk_abi_version(void);

/**
 * Releases an owned byte buffer returned by Rust.
 */
void rk_bytes_free(struct RkBytes bytes);

/**
 * Releases an owned UTF-8 string buffer returned by Rust.
 */
void rk_string_free(struct RkBytes string);

/**
 * Serializes an error as UTF-8 JSON owned by the caller.
 *
 * # Safety
 *
 * `error` must be null or a live `RkError` returned by this library.
 */
struct RkBytes rk_error_json(const struct RkError *error);

/**
 * Releases an owned error handle.
 *
 * # Safety
 *
 * `error` must be null or an `RkError` returned by this library that has not
 * already been freed.
 */
void rk_error_free(struct RkError *error);

/**
 * Creates a runner and waits for bounded, management-API-confirmed engine
 * registration before returning its owned handle.
 *
 * # Safety
 *
 * `config` must be null when `config_len` is zero or point to
 * `config_len` readable bytes for this call.
 */
struct RkRunnerResult rk_runner_new(const uint8_t *config, size_t config_len);

/**
 * Releases a runner handle, forcing a bounded drain if shutdown was omitted.
 *
 * # Safety
 *
 * `runner` must be null or a live handle returned by `rk_runner_new` that has
 * not already been freed. No other call may borrow it concurrently.
 */
void rk_runner_free(struct RkRunner *runner);

/**
 * Polls a runner for an encoded EventBatch.
 *
 * # Safety
 *
 * `runner` must be a live handle for the duration of this call.
 */
struct RkPollResult rk_runner_poll(struct RkRunner *runner, uint32_t timeout_ms);

/**
 * Submits an encoded CommandBatch without blocking on command execution.
 *
 * # Safety
 *
 * `runner` must be live and `batch` must satisfy the borrowed-buffer rules.
 */
struct RkSubmitResult rk_runner_submit(struct RkRunner *runner, const uint8_t *batch, size_t len);

/**
 * Begins graceful shutdown; polling continues through RunnerStopped.
 *
 * # Safety
 *
 * `runner` must be a live handle for the duration of this call.
 */
struct RkSubmitResult rk_runner_shutdown(struct RkRunner *runner, uint32_t deadline_ms);

#endif  /* RIVETKIT_GO_FFI_H */
