#ifndef RIVETKIT_GO_FFI_H
#define RIVETKIT_GO_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The single source of truth for the native ABI version.
 */
#define RK_ABI_VERSION 1

/**
 * Opaque structured error handle. Its contents are accessed as JSON.
 */
typedef struct RkError RkError;

/**
 * Opaque runner handle. M0 never creates one.
 */
typedef struct RkRunner RkRunner;

/**
 * An owned byte buffer allocated by Rust.
 */
typedef struct RkBytes {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} RkBytes;

typedef struct RkRunnerResult {
  struct RkRunner *runner;
  struct RkError *err;
} RkRunnerResult;

typedef struct RkPollResult {
  struct RkBytes payload;
  struct RkError *err;
} RkPollResult;

typedef struct RkSubmitResult {
  struct RkError *err;
} RkSubmitResult;

/**
 * Returns the native ABI version expected by the generated Go binding.
 */
uint32_t rk_abi_version(void);

/**
 * Releases an owned byte buffer returned by Rust.
 */
void rk_bytes_free(struct RkBytes bytes);

/**
 * Releases an owned UTF-8 string buffer returned by Rust.
 */
void rk_string_free(struct RkBytes string);

/**
 * Serializes an error as UTF-8 JSON owned by the caller.
 *
 * # Safety
 *
 * `error` must be null or a live `RkError` returned by this library.
 */
struct RkBytes rk_error_json(const struct RkError *error);

/**
 * Releases an owned error handle.
 *
 * # Safety
 *
 * `error` must be null or an `RkError` returned by this library that has not
 * already been freed.
 */
void rk_error_free(struct RkError *error);

/**
 * Creates a runner. M0 returns a structured not-implemented error.
 */
struct RkRunnerResult rk_runner_new(const uint8_t *_config, size_t _config_len);

/**
 * Releases a runner handle. M0 has no constructible runner handles.
 */
void rk_runner_free(struct RkRunner *_runner);

/**
 * Polls a runner. M0 returns a structured not-implemented error.
 */
struct RkPollResult rk_runner_poll(struct RkRunner *_runner, uint32_t _timeout_ms);

/**
 * Submits a command batch. M0 returns a structured not-implemented error.
 */
struct RkSubmitResult rk_runner_submit(struct RkRunner *_runner, const uint8_t *_batch, size_t len);

/**
 * Begins graceful shutdown. M0 returns a structured not-implemented error.
 */
struct RkSubmitResult rk_runner_shutdown(struct RkRunner *_runner, uint32_t _deadline_ms);

#endif  /* RIVETKIT_GO_FFI_H */
